[workspace]
resolver = "2"
members = [
  "ui-theme",
  "skyscope-design-system-demo",
  "web-demo",
  "ui-storybook",
]

[workspace.dependencies]
egui = "0.34"
egui_flex = "0.6"
eframe = { version = "0.34", default-features = false }
serde = { version = "1", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
