[package]
name = "skyscope-design-system-demo"
version = "0.1.0"
edition = "2021"
publish = false
description = "Private native and web demo app for Skyscope Design System"

[dependencies]
skyscope-design-system = { path = "../ui-theme", features = ["composites"] }
eframe = { workspace = true, features = [
    "default_fonts",
    "wayland",
    "wgpu",
    "x11",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = { workspace = true }
