[package]
name = "web-demo"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
frost-night-egui = { path = "../ui-theme", features = ["demo"] }
eframe = { workspace = true, features = [
    "default_fonts",
    "wayland",
    "wgpu",
    "x11",
] }
log = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = ["Document", "Window", "HtmlCanvasElement", "Element"] }
